PlanningGenerator/config/routes.rb
Rails.application.routes.draw do

    get '/' => 'home#show'
    post 'disponibilites/create'

    get 'disponibilites/fin'
    get 'disponibilites/rm_dispos'
    resources :events do
    end
    resources :participants do
    end
    resources :disponibilites do
    end
    resources :creneaus do
    end

end

PlanningGenerator/app/models/participant.rb
class Participant < ActiveRecord::Base
	belongs_to :event
	has_many :disponibilites
	has_many :creneaus, :through => :disponibilites
	validates_associated :event
	validates :nom, presence: true, uniqueness: true
end

PlanningGenerator/app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
	def index
	end

	def new
		@participant = Participant.new
		@event = Event.new
		@event_en_cours = Event.last
	end
	def create
		@event = Event.new(event_params)
		if ((event_params[:participants_attributes].count) != (Event.last.Nombre_de_Participants))
			@event.errors.add(:participant, "Pas le bon nombre de participans !")
			render 'new'
		else
			event_params[:participants_attributes].each do |part|
				params_boxes = event_params.except(:_destroy)
				@nparti = Participant.new(part.second.except(:_destroy))
				@nparti.event_id = Event.last.id
				@nparti.save
			end
		redirect_to new_disponibilite_path
		end
	end
	def edit
		@participant = Participant.find(params[:id])
	end
	def update
		@participant = Participant.find(params[:id])
			if @participant.update(participant_params)
  		  			redirect_to participants_path
  		  	else
  		  			render 'edit'
  		  	end
	end



	 private 
  		def event_params
  			params.require(:event).permit!
  			#(:Nom, :Nombre_de_Participants, :Nombre_de_Creneaux, :Nombre_de_Creneaux_par_Participant, :event_id, creneaus_attributes: [:id, :date_fin, :date_debut, :Nombre_de_Participants_Necessaires, :_destroy], participants_attributes: [:id, :nom, :event_id, :_destroy])
  		end
  		def participant_params
  			params.require(:participant).permit(:nom)
  		end
end

PlanningGenerator/app/helpers/participants_helper.rb
module ParticipantsHelper
end

PlanningGenerator/app/views/participants/edit.html.erb
<div class="row">
      <% if @participant.errors.any? %>        
          <div id="error_explanation" class="col-sm-6  btn-danger">
            <h4>
              La modification du participant est impossible : 
            </h4>
            <ul>
              <% @participant.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
       <%end%>
</div>
</br>
<div class="row">
<%= form_for @participant, html: {class: "form-horizontal"} do |f| %>
	 <div class="form-group">
	            <%= f.label :nom, "Nom", :class => "col-sm-2 control-label"%>
	            <div class="col-sm-4">
	            	<%= f.text_field :nom, :class => "form-control"%>
	            </div>
	 </div>
	 <div class="col-sm-offset-2 col-sm-4">
	    <%=  button_tag(type: 'submit', class: "btn btn-primary") do %>
	    	<i class="icon-ok icon-white"></i> Sauvegarder
	    	<%end%>
   <%= link_to "Retour", participants_path, :class => "btn btn-default"%>
	</div>
<%end%>
</div>

PlanningGenerator/app/views/participants/index.html.erb
<h1>Liste des Participants </h1>
<div class="row">
<table class = "table table-striped table-bordered">
   <tr>
       <th>Nom</th>
       <th>Évènement</th>
   </tr>
   <% Participant.all.each do |p| %>
   <tr>
       <td><%=p.nom%></td>
       <td><%=p.event.Nom%></td>
       <td><%= link_to "Modifier", edit_participant_path(p), :class => "btn btn-warning"%></td>
   </tr>
   <%end%>
</table>
</div>

PlanningGenerator/app/views/participants/new.html.erb
<h1> Choix des Participants </h1>
<h4> Rappel : Il y a <%=@event_en_cours.Nombre_de_Participants%> participant(s) à entrer pour : <%=@event_en_cours.Nom%>.</h4>

<div class ="row">
<%= javascript_include_tag :defaults, "nested_form" %>
<% if @event.errors.any? %>        
      <div id="error_explanation" class="col-sm-6  btn-danger">
        <h4>
          La modification de l'évènement est impossible : 
        </h4>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <%end%>
</div>
<div class ="row">
    <div class="col-sm-6">
      <%= nested_form_for @event, url: {action: "create"} do |f| %>
        <div class="form-inline">
          <%= f.fields_for :participants do |participant_form| %> 
          <div class="form-group">
            <%= participant_form.label :nom %>
            <%= participant_form.date_field :nom, :class => "form-control"%></br>
          </div>
          <%= participant_form.link_to_remove "Enlever ce Participant",:class => "center btn btn-danger"%>
        </div>
      <% end %></br>
      <h4><%= f.link_to_add "Ajouter un Participant", :participants, :class =>"btn btn-primary h3"%></h4>
    </div>
</div>
<div class="row">
    <div class="col-sm-9" style="padding: 30px">
      <%=  button_tag(type: 'submit', class: "btn btn-success") do %>
          Sauvegarder
      <%end%>
    <%end%>
    <%= link_to "Modifier L'Évènement", edit_event_path(@event_en_cours), :class => "btn btn-warning"%>
    <%= link_to "Modifier Les Créneaux", creneaus_path, :class => "btn btn-warning"%>
    </div>
</div>

PlanningGenerator/app/views/participants/show.html.erb
<p>
  <strong>Nom :</strong>
  <%=@participant.nom %>
</p>
<p>
  <strong>Evenement :</strong>
  <%=Event.find(@participant.event_id).Nom%>
</p>