PlanningGenerator/config/routes.rb
Rails.application.routes.draw do

    get '/' => 'home#show'
    post 'disponibilites/create'

    get 'disponibilites/fin'
    get 'disponibilites/rm_dispos'
    resources :events do
    end
    resources :participants do
    end
    resources :disponibilites do
    end
    resources :creneaus do
    end

end

PlanningGenerator/app/models/creneau.rb
class Creneau < ActiveRecord::Base
	belongs_to :event
	has_many :disponibilites
	has_many :participants, :through => :disponibilites
	validates_associated :event
	validates :date_fin, :presence => "true"
	validates :date_debut, :presence => "true"
	validates :Nombre_de_Participants_Necessaires, presence: true
end

PlanningGenerator/app/controllers/creneau_controller.rb
class CreneauController < ApplicationController

	def index

	end

	def edit
		
	end
end

PlanningGenerator/app/controllers/creneaus_controller.rb
class CreneausController < ApplicationController

	def index

	end

	def edit
		@creneau = Creneau.find(params[:id])
		@event = Event.last
	end
	def update
		@creneau = Creneau.find(params[:id])
			if @creneau.update(creneau_params)
  		  			redirect_to creneaus_path
  		  	else
  		  			render 'edit'
  		  	end
	end
	def creneau_params
  			params.require(:creneau).permit(:date_debut, :date_fin, :Nombre_de_Participants_Necessaires)
  		end
end

PlanningGenerator/app/helpers/creneau_helper.rb
module CreneauHelper
end

PlanningGenerator/app/views/creneaus/edit.html.erb
<div class="row">
      <% if @creneau.errors.any? %>        
          <div id="error_explanation" class="col-sm-6  btn-danger">
            <h4>
              La modification du Creneau est impossible : 
            </h4>
            <ul>
              <% @creneau.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
       <%end%>
</div>
</br>
<div class="row">
  <%= form_for @creneau, html: {class: "form-horizontal"} do |f| %>
        <script type="text/javascript">
                  $('.datetimepicker').datetimepicker({format: '20YY-MM-DD HH:mm'});
        </script>
        <div class="form-group">
            <%= f.label :date_debut, :class => "col-sm-2 control-label"%>
            <div class="col-sm-3">
                <%= f.date_field :date_debut , :class => "form-control datetimepicker"%> 
            </div>
        </div>
        <div class="form-group">
            <%= f.label :date_fin, :class => "col-sm-2 control-label"%>
            <div class="col-sm-3">
                <%= f.date_field :date_fin , :class => "form-control datetimepicker"%> 
            </div>
        </div>
        <div class="form-group">
            <%= f.label :Nombre_de_Participants_Necessaires, "Nombre De Participants", :class => "col-sm-2 control-label"%>
            <div class="col-sm-3">
                <%= f.text_field :Nombre_de_Participants_Necessaires, :class => "form-control"%>
            </div>
        </div>
   <div class="col-sm-offset-2 col-sm-4">
      <%=  button_tag(type: 'submit', class: "btn btn-primary") do %>
        <i class="icon-ok icon-white"></i> Sauvegarder
        <%end%>
      <%= link_to "Retour", creneaus_path, :class => "btn btn-default"%>
  </div>
  <%end%>
</div>

PlanningGenerator/app/views/creneaus/index.html.erb
<h1>Liste des Créneaux </h1>
<div class="row">
<table class = "table table-striped table-bordered">
   <tr>
       <th>Heure de Début</th>
       <th>Heure de Fin</th>
       <th>Nombre de Participants</th>
   </tr>
   <% Creneau.all.each do |c| %>
   <tr>
       <td><%=c.date_debut.strftime("%m/%d/%Y : %H:%M")%></td>
       <td><%=c.date_fin.strftime("%m/%d/%Y : %H:%M")%></td>
       <td><%=c.Nombre_de_Participants_Necessaires%></td>
       <td><%= link_to "Modifier", edit_creneau_path(c), :class => "btn btn-warning"%></td>
   </tr>
   <%end%>
</table>
</div>